pipeline:
  test:
    image: node
    commands:
      - npm install --quiet
      - npm run build
    when:
      branch: master
      event: pull_request

  publish:
    image: plugins/docker
    repo: devheavenci/portal
    tags: "${DRONE_COMMIT_SHA:0:8}"
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push

  deploy:
    image: quay.io/honestbee/drone-kubernetes
    namespace: portal
    deployment: portal-deployment
    repo: devheavenci/portal
    container: portal
    tag: "${DRONE_COMMIT_SHA:0:8}"
    secrets: [ kubernetes_server, kubernetes_token, kubernetes_cert ]
    when:
      branch: master
      event: push

branches: master